SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCALING = 1.0

# Параметры игрока
PLAYER_MAX_HEALTH = 100.0
PLAYER_SPEED = 3.0
PLAYER_INVINCIBILITY_TIME = 3.0
PLAYER_MAX_MANA = 100.0
PLAYER_MELEE_DAMAGE = 4.0
PLAYER_RANGE_DAMAGE = 8.0
PLAYER_RANGE_MANA_COST = 2.0
PLAYER_RANGE_SPEED = 5.0
PLAYER_ATTACK_COOLDOWN_TIME = 0.4
PLAYER_DASH_SPEED_MULTIPLIER = 5
PLAYER_DASH_DURATION = 0.1
PLAYER_DASH_COOLDOWN = 1.0
PLAYER_NORMAL_ALPHA = 255
PLAYER_FLASH_ALPHA = 64
PLAYER_WALK_ANIMATION_DELAY = 0.075
PLAYER_INPUT_LOCK_AFTER_MELEE_ATTACK_TIME = 0.2
PLAYER_MANA_PER_HIT = 1

# --- Враги ---
# Warrior
WARRIOR_DAMAGE = 4
WARRIOR_SPEED = 1
WARRIOR_MAX_HEALTH = 25
WARRIOR_MELEE_ATTACK_DISTANCE = 65
WARRIOR_ATTACK_COOLDOWN = 0.7
WARRIOR_LOCK_AFTER_TAKING_DAMAGE_TIME = 0.2
WARRIOR_WALK_ANIMATION_DELAY = 0.075

# Barbarian
BARBARIAN_MELEE_DAMAGE = 4
BARBARIAN_RANGE_DAMAGE = 8
BARBARIAN_SPEED = 1.5
BARBARIAN_RANGE_SPEED = 12
BARBARIAN_MAX_HEALTH = 25
BARBARIAN_MELEE_ATTACK_DISTANCE = 85
BARBARIAN_ATTACK_COOLDOWN = 1.2
BARBARIAN_LOCK_AFTER_TAKING_DAMAGE_TIME = 0.2
BARBARIAN_WALK_ANIMATION_DELAY = 0.075
BARBARIAN_RANGE_ATTACK_DISTANCE = 230